/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.3.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Account {
    id: number;
    accountName: string;
    displayName: string;
    profileImageUrl?: string;
    isFriend: boolean;
    friendRequestInProgress: boolean;
    following: boolean;
    isFollower: boolean;
    followingCount: number;
    followerCount: number;
    friendCount: number;
    feedCount: number;
    muting: boolean;
    blocking: boolean;
    web?: string;
    birthday?: number;
    location?: string;
    bio?: string;
    joinedAt?: number;
    next?: number;
}
