/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Message } from './message';


export interface Channel {
    id: number;
    name?: string;
    message?: Message;
    invitationOnly: boolean;
    privacyType: Channel.PrivacyTypeEnum;
    authorityType: Channel.AuthorityTypeEnum;
    userCount: number;
    lastPostedAt?: number;
    organizedAt: number;
    next?: number;
}
export namespace Channel {
    export type PrivacyTypeEnum = 'everyone' | 'follows' | 'followers' | 'friends';
    export const PrivacyTypeEnum = {
        Everyone: 'everyone' as PrivacyTypeEnum,
        Follows: 'follows' as PrivacyTypeEnum,
        Followers: 'followers' as PrivacyTypeEnum,
        Friends: 'friends' as PrivacyTypeEnum
    }
    export type AuthorityTypeEnum = 'organizer' | 'member';
    export const AuthorityTypeEnum = {
        Organizer: 'organizer' as AuthorityTypeEnum,
        Member: 'member' as AuthorityTypeEnum
    }
}
