/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Comment {
    id: number;
    replyId?: number;
    tweetId: number;
    message: string;
    user: User;
    likeCount: number;
    warning: boolean;
    rejected: boolean;
    postedAt: number;
    next: number;
}
