/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.3.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';


export interface Comment {
    id: number;
    replyId?: number;
    message: string;
    account: Account;
    likeCount: number;
    contentWarning: boolean;
    contentDeleted: boolean;
    postedAt: number;
    next?: number;
}
