/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.3.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';


export interface FriendRequest {
    id: number;
    account: Account;
    requestStatus: FriendRequest.RequestStatusEnum;
    requestedAt: number;
    next?: number;
}
export namespace FriendRequest {
    export type RequestStatusEnum = 'noResponded' | 'accepted' | 'rejected';
    export const RequestStatusEnum = {
        NoResponded: 'noResponded' as RequestStatusEnum,
        Accepted: 'accepted' as RequestStatusEnum,
        Rejected: 'rejected' as RequestStatusEnum
    }
}
