/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.3.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Group } from './group';


export interface GroupInvitation {
    id: number;
    group: Group;
    account: Account;
    invitationStatus: GroupInvitation.InvitationStatusEnum;
    invitedAt: number;
    next?: number;
}
export namespace GroupInvitation {
    export type InvitationStatusEnum = 'noResponded' | 'accepted' | 'rejected';
    export const InvitationStatusEnum = {
        NoResponded: 'noResponded' as InvitationStatusEnum,
        Accepted: 'accepted' as InvitationStatusEnum,
        Rejected: 'rejected' as InvitationStatusEnum
    }
}
