/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Information {
    id: number;
    informationType: Information.InformationTypeEnum;
    contentId?: number;
    message: string;
    url: string;
    notifiedAt: number;
    next: number;
}
export namespace Information {
    export type InformationTypeEnum = 'operator' | 'invitation' | 'friendRequest' | 'tweet' | 'tweetReply' | 'commentReply';
    export const InformationTypeEnum = {
        Operator: 'operator' as InformationTypeEnum,
        Invitation: 'invitation' as InformationTypeEnum,
        FriendRequest: 'friendRequest' as InformationTypeEnum,
        Tweet: 'tweet' as InformationTypeEnum,
        TweetReply: 'tweetReply' as InformationTypeEnum,
        CommentReply: 'commentReply' as InformationTypeEnum
    }
}
