/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.3.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Medium {
    id: number;
    uri: string;
    width: number;
    height: number;
    size: number;
    thumbnailUrl?: string;
    mediumType: Medium.MediumTypeEnum;
    contentWarning: boolean;
    contentDeleted: boolean;
}
export namespace Medium {
    export type MediumTypeEnum = 'image' | 'movie';
    export const MediumTypeEnum = {
        Image: 'image' as MediumTypeEnum,
        Movie: 'movie' as MediumTypeEnum
    }
}
