/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Medium } from './medium';
import { User } from './user';


export interface Message {
    id: number;
    channelId: number;
    messageType: Message.MessageTypeEnum;
    message?: string;
    medium?: Medium;
    user: User;
    unread: boolean;
    userCount: number;
    readUserCount: number;
    warning: boolean;
    rejected: boolean;
    postedAt: number;
    next: number;
}
export namespace Message {
    export type MessageTypeEnum = 'text' | 'medium' | 'stamp' | 'invited' | 'joined' | 'left';
    export const MessageTypeEnum = {
        Text: 'text' as MessageTypeEnum,
        Medium: 'medium' as MessageTypeEnum,
        Stamp: 'stamp' as MessageTypeEnum,
        Invited: 'invited' as MessageTypeEnum,
        Joined: 'joined' as MessageTypeEnum,
        Left: 'left' as MessageTypeEnum
    }
}
