/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.9.4-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Notification {
    id: number;
    notificationType: Notification.NotificationTypeEnum;
    contentId?: number;
    message: string;
    url: string;
    notifiedAt: number;
    next: number;
}
export namespace Notification {
    export type NotificationTypeEnum = 'operator' | 'invitation' | 'friendRequest' | 'feed' | 'feedReply' | 'commentReply';
    export const NotificationTypeEnum = {
        Operator: 'operator' as NotificationTypeEnum,
        Invitation: 'invitation' as NotificationTypeEnum,
        FriendRequest: 'friendRequest' as NotificationTypeEnum,
        Feed: 'feed' as NotificationTypeEnum,
        FeedReply: 'feedReply' as NotificationTypeEnum,
        CommentReply: 'commentReply' as NotificationTypeEnum
    }
}
