/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PostSignUpBody {
    /**
     * Auth type.
     */
    authType: PostSignUpBody.AuthTypeEnum;
    /**
     * User name or email address.
     */
    identifier: string;
    /**
     * User password.
     */
    password: string;
}
export namespace PostSignUpBody {
    export type AuthTypeEnum = 'username' | 'email';
    export const AuthTypeEnum = {
        Username: 'username' as AuthTypeEnum,
        Email: 'email' as AuthTypeEnum
    }
}
