/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PushNotificationSetting {
    feed: boolean;
    comment: boolean;
    friendRequest: boolean;
    message: boolean;
    groupMessage: boolean;
    groupInvitation: boolean;
    showMessage: boolean;
}
