/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PutChannelBody {
    /**
     * Channel name.
     */
    name: string;
    /**
     * Only invited users can join in.
     */
    byInvitationOnly: boolean;
    /**
     * Which users can join in.
     */
    privacyType: PutChannelBody.PrivacyTypeEnum;
    /**
     * Which users can manage a channel.
     */
    authorityType: PutChannelBody.AuthorityTypeEnum;
}
export namespace PutChannelBody {
    export type PrivacyTypeEnum = 'everyone' | 'follows' | 'followers' | 'friends';
    export const PrivacyTypeEnum = {
        Everyone: 'everyone' as PrivacyTypeEnum,
        Follows: 'follows' as PrivacyTypeEnum,
        Followers: 'followers' as PrivacyTypeEnum,
        Friends: 'friends' as PrivacyTypeEnum
    }
    export type AuthorityTypeEnum = 'organizer' | 'member';
    export const AuthorityTypeEnum = {
        Organizer: 'organizer' as AuthorityTypeEnum,
        Member: 'member' as AuthorityTypeEnum
    }
}
