/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PutDeviceBody {
    /**
     * Device status.
     */
    status: PutDeviceBody.StatusEnum;
    /**
     * Unique Device Identifier.
     */
    udid: string;
    /**
     * Push notification token.
     */
    pushToken?: string;
}
export namespace PutDeviceBody {
    export type StatusEnum = 'active' | 'inactive';
    export const StatusEnum = {
        Active: 'active' as StatusEnum,
        Inactive: 'inactive' as StatusEnum
    }
}
