/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PutGroupBody {
    /**
     * Group name.
     */
    name: string;
    /**
     * Only invited accounts can join in.
     */
    byInvitationOnly: boolean;
    /**
     * Which accounts can join in.
     */
    privacyType: PutGroupBody.PrivacyTypeEnum;
    /**
     * Which accounts can manage a group.
     */
    authorityType: PutGroupBody.AuthorityTypeEnum;
}
export namespace PutGroupBody {
    export type PrivacyTypeEnum = 'everyone' | 'following' | 'followers' | 'friends';
    export const PrivacyTypeEnum = {
        Everyone: 'everyone' as PrivacyTypeEnum,
        Following: 'following' as PrivacyTypeEnum,
        Followers: 'followers' as PrivacyTypeEnum,
        Friends: 'friends' as PrivacyTypeEnum
    }
    export type AuthorityTypeEnum = 'owner' | 'member';
    export const AuthorityTypeEnum = {
        Owner: 'owner' as AuthorityTypeEnum,
        Member: 'member' as AuthorityTypeEnum
    }
}
