/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PutNotificationSettingBody {
    /**
     * Notice new follower feed arrived.
     */
    feed: boolean;
    /**
     * Notice new comment arrived.
     */
    comment: boolean;
    /**
     * Notice new friend request arrived.
     */
    friendRequest: boolean;
    /**
     * Notice new message arrived.
     */
    message: boolean;
    /**
     * Notice new group message arrived.
     */
    groupMessage: boolean;
    /**
     * Notice new group groupInvitation arrived.
     */
    groupInvitation: boolean;
    /**
     * Show messages text on notification.
     */
    showMessage: boolean;
}
