/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Medium } from './medium';
import { User } from './user';


export interface Tweet {
    id: number;
    message: string;
    mediums: Array<Medium>;
    tags?: Array<string>;
    user?: User;
    likeCount: number;
    commentCount: number;
    liked: boolean;
    warning: boolean;
    rejected: boolean;
    postedAt: number;
    next: number;
}
