/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User {
    id: number;
    userName: string;
    displayName: string;
    profileImageUrl?: string;
    isFriend: boolean;
    friendRequestInProgress: boolean;
    follow: boolean;
    isFollower: boolean;
    followCount: number;
    followerCount: number;
    friendCount: number;
    tweetCount: number;
    muted: boolean;
    blocked: boolean;
    web?: string;
    birthday?: number;
    location?: string;
    bio?: string;
    joinedAt?: number;
    userStatus: User.UserStatusEnum;
    signedOutAt?: number;
    next: number;
}
export namespace User {
    export type UserStatusEnum = 'normally' | 'deleted' | 'terminated';
    export const UserStatusEnum = {
        Normally: 'normally' as UserStatusEnum,
        Deleted: 'deleted' as UserStatusEnum,
        Terminated: 'terminated' as UserStatusEnum
    }
}
