/**
 * Cactacea backend API
 * Cactacea / Cactacea backend API for web and mobile applications
 *
 * OpenAPI spec version: 19.3.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Authentication } from '../model/authentication';
import { CactaceaErrors } from '../model/cactaceaErrors';
import { PostSignUpBody } from '../model/postSignUpBody';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SessionsService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Sign in
     * 
     * @param accountName Account name.
     * @param password Account password.
     * @param udid Unique Device Identifier.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public signIn(accountName: string, password: string, udid: string, observe?: 'body', reportProgress?: boolean): Observable<Authentication>;
    public signIn(accountName: string, password: string, udid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Authentication>>;
    public signIn(accountName: string, password: string, udid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Authentication>>;
    public signIn(accountName: string, password: string, udid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountName === null || accountName === undefined) {
            throw new Error('Required parameter accountName was null or undefined when calling signIn.');
        }
        if (password === null || password === undefined) {
            throw new Error('Required parameter password was null or undefined when calling signIn.');
        }
        if (udid === null || udid === undefined) {
            throw new Error('Required parameter udid was null or undefined when calling signIn.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (accountName !== undefined) {
            queryParameters = queryParameters.set('accountName', <any>accountName);
        }
        if (password !== undefined) {
            queryParameters = queryParameters.set('password', <any>password);
        }
        if (udid !== undefined) {
            queryParameters = queryParameters.set('udid', <any>udid);
        }

        let headers = this.defaultHeaders;

        // authentication (api_key) required
        if (this.configuration.apiKeys["X-API-KEY"]) {
            headers = headers.set('X-API-KEY', this.configuration.apiKeys["X-API-KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Authentication>(`${this.basePath}/sessions`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Sign up
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public signUp(body: PostSignUpBody, observe?: 'body', reportProgress?: boolean): Observable<Authentication>;
    public signUp(body: PostSignUpBody, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Authentication>>;
    public signUp(body: PostSignUpBody, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Authentication>>;
    public signUp(body: PostSignUpBody, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling signUp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Authentication>(`${this.basePath}/sessions`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
